# Generated by Django 5.2.1 on 2025-05-20 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('posicion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('alias', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('localizacion', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control.jugador')),
            ],
        ),
    ]
